CLASS_NAME = {
    'batik-bali': 'Batik Bali',
    'batik-betawi': 'Batik Betawi',
    'batik-celup': 'Batik Celup', 
    'batik-cendrawasih': 'Batik Cendrawasih',
    'batik-ceplok': 'Batik Ceplok',
    'batik-ciamis': 'Batik Ciamis',
    'batik-garutan': 'Batik Garutan',
    'batik-gentongan': 'Batik Gentongan',
    'batik-kawung': 'Batik Kawung',
    'batik-keraton': 'Batik Keraton',
    'batik-lasem': 'Batik Lasem',
    'mega-mendung': 'Mega Mendung',
    'batik-parang': 'Batik Parang',
    'batik-pekalongan': ' Batik Pekalongan',
    'batik-priangan': 'Batik Priangan',
    'batik-sekar': 'Batik Sekar',
    'batik-sidoluhur': 'Batik Sidoluhur',
    'batik-sidomukti': 'Batik Sidomukti',
    'batik-sogan': 'Batik Sogan',
    'batik-tambal': 'Batik Tambal'
}